name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: [2.13.x]
        java-version: [17]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        run: sbt ++${{ matrix.scala-version }} clean test
